### PR TITLE
[noconflict] Add option to provide full Quill options object

### PR DESCRIPTION
**Pull request by nkonev**
Non-conflict version of https://github.com/davidroyer/vue2-editor/pull/43 with some fixes

### CODE REVIEW

**Comment by jsonhuntrods** [comment]
I agree this would be nice

**Comment by shawjb** [comment]
:+1: Very helpful

**Comment by mitchellmurry** [comment]
This would be awesome!

**Comment by pkellen** [comment]
:shipit:

**Comment by nkonev** [comment]
Ping @davidroyer

**Comment by davidroyer** [comment]
@nkonev Nice work and thank you for the contribution!

**Pull request merged**
