### PR TITLE
feat(nuxt): Add nuxt module

### PR DESCRIPTION
**Pull request by ricardogobbosouza**
Module for [Nuxt.js](https://nuxtjs.org/)

```js
// nuxt.config.js
{
  modules: [
    'vue2-editor/nuxt'
  ]
}
```

### CODE REVIEW

**Comment by ricardogobbosouza** [comment]
Hi @davidroyer,
I believe that it would help a lot to implement `Vue2Editor` on [Nuxt.js](https://nuxtjs.org/)

**Comment by ricardogobbosouza** [comment]
ping @davidroyer

**Comment by rajesh-h** [comment]
@ricardogobbosouza  could you please confirm is vue2editor works on Nuxt when we want to add/edit images?
I am getting error when I import Quill.
Your help is much appreciated. I have raised issue as well. But not sure will I get any response. so just trying luck here

https://github.com/davidroyer/vue2-editor/issues/210

**Comment by ricardogobbosouza** [comment]
@rajesh-h I am going to release a mono-repo in the nuxt community with various editor types.

**Comment by adambergman** [comment]
Using your branch in a project I'm working on. It's working flawlessly with Nuxt. Thanks for this, hope it gets merged soon.

**Comment by rajesh-h** [comment]
@adambergman which repository are you talking about?

**Comment by rajesh-h** [comment]
I am still having issue with same error.

1. I removed the existing vue2-editor
2. Installed fresh copy of vue2-editor from @ricardogobbosouza nuxt-module branch
3. made changes on nuxt-config.js  by removing import as plugin and adding as Modules as specified in the first comment on this thread.
4. My example is the default example shown as here [Example - Basic Setup](https://github.com/ricardogobbosouza/vue2-editor/tree/nuxt-module#example---basic-setup)

Am I missing something here?

**Comment by adambergman** [comment]
@rajesh-h I did the following.

1. `yarn add https://github.com/ricardogobbosouza/vue2-editor.git#nuxt-module`
2. Added the plugin `'vue2-editor/nuxt'` to my modules array in nuxt.config.js
3. Wrapped the `<vue-editor>` tag in `<client-only>` tags

Maybe you forgot to specify the branch with `#nuxt-module` at the end?

**Pull request closed without merging**
